on:
  workflow_dispatch:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build-and-scrape-site:
    name: Deploy and scrape static site
    runs-on: ubuntu-latest

    steps:
      - name: Run Docker container
        run: |
          docker run -e "APPLICATION_ID=${{ secrets.APPLICATION_ID }}" -e "ALGOLIA_API_KEY=${{ secrets.ALGOLIA_API_KEY }}" -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper